<?php

//hook_init
function custom_module_init() {

//    drupal_set_message("Hello");
}

function custom_module_menu() {

    $items = array();

    $items['Hellopage'] = array(
      'title' => 'TGDR Development',
      'description' => 'Hello, Users',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('custom_module_showCustomModuleForm'),
      'access callback' => 'user_access',
      'access arguments' => array('access content'),
      'type' => MENU_NORMAL_ITEM
    );

    $items['getHello'] = array(
      'page callback' => 'custom_module_ajaxCallHandler',
      'access callback' => 'user_access',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK
    );

    return $items;
}

//This function is only necessary when using AJAX
function custom_module_ajaxCallHandler() {

    global $user;

    if (empty($_GET['token']) || !drupal_valid_token($_GET['token'], 'my secret value' . $user->uid)) {
        return MENU_ACCESS_DENIED;
    }

    echo "Hello, " . filter_xss($_GET['name']) . "!";
}

/* This function is what shows the form to the user
 * It contains all of the form elements. 
 */


function custom_module_showCustomModuleForm() {

    $form['primaryAuthor'] = array(                                             //Add a 
      '#type' => 'select',
      '#title' => t('Primary Author'),
      '#options' => array(
        0 => t('Author 0'),
        1 => t('Author 1'),
        2 => t('Author 2'),
        3 => t('Author 3'),
      ),
      '#required' => true,
//      '#default_value' => 0,
      );
    
    $form['#suffix'] = '<input type="button" id="button" value="Add Author"><br/><div id="msg-display-area"></div>';
    
    for($i = 0; $i < 30; $i++){
       if ($i == 0){
            $form['secondaryAuthorForm' . $i] = array(
      '#prefix' => '<div id= secondaryAuthor' . $i . '>',
      '#type' => 'select',
      '#title' => t('Seconday Author'),
      '#options' => array(
        0 => t('Author 0'),
        1 => t('Author 1'),
        2 => t('Author 2'),
        3 => t('Other'),
      ),
      '#default_value' => 0,
      );
       
       $form['secondaryAuthorCustomForm' . $i] = array(
      '#suffix' => '</div>',
      '#type' => 'textfield',
      '#disabled' => true,
      '#default_value' => '',
      );   
       }
       else{
       $form['secondaryAuthorForm' . $i] = array(
      '#prefix' => '<div id= secondaryAuthor' . $i . '>',
      '#type' => 'select',
      '#options' => array(
        0 => t('--Secondary Author--'),
        1 => t('Author 1'),
        2 => t('Author 2'),
        3 => t('Other'),
      ),
      );
       
       $form['secondaryAuthorCustomForm' . $i] = array(
      '#suffix' => '</div>',
      '#type' => 'textfield',
      '#disabled' => true,
      '#default_value' => '',
      );
       }
    }
    
//  change the enable with jQuery -  do NOT alter the settings of other forms with jQuery. 
    
    $form['organization'] = array(
      '#type' => 'select',
      '#title' => t('Organization'),
      '#options' => array(
        0 => t('--Organization--'),
        1 => t('Organization 0'),
        2 => t('Organization 1'),
        3 => t('Organization 2'),
      ),
      '#required' => true,
    );
 
    $form['publicationStatus'] = array(
      '#type' => 'select',
      '#title' => t('Publication Status'),
      '#options' => array(
        0 => t('--Publication Status--'),
        1 => t('In Preparation'),
        2 => t('Submitted'),
        3 => t('In press'),
        4 => t('Published'),
      ),
      '#required' => true,
      '#default_value' => 4,
    );
    
    $form['year'] = array(
      '#type' => 'select',
      '#title' => t('Year'),
      '#options' => array(
        0 => t('--Year--'),
        1 => t('1994'),
        2 => t('1995'),
        3 => t('1996'),
        4 => t('1997'),
      ),
      '#required' => true,
      '#default_value' => 0,
    );
    
     $form['title'] = array(
       '#type' => 'textfield',
       '#title' => t('Title'),
       '#required' => true,
     );
     
     $form['abstract'] = array(
       '#type' => 'textfield',
       '#title' => t('Abstract'),
       '#required' => true,
     );
     
     $form['journal'] = array(
       '#type' => 'select',
       '#type' => t('Journal'),
       '#options' => array(
         0 => '--Journal--',
         1 => 'Journal 1',
         2 => 'Journal 2',
         3 => 'Journal 3',
       ),
       '#required' => true,
     );
     
      $form['speciesNumber'] = array(
      '#type' => 'select',
      '#title' => t('Please Select the Number of Species under Study'),
      '#options' => array(
        1 => t('1'),
        2 => t('2'),
        3 => t('3'),
        4 => t('4'),
        5 => t('5'),
        6 => t('6'),
        7 => t('7'),
        8 => t('8'),
        9 => t('9'),
        10 => t('10'),
      ),
      '#default_value' => 1,
    );
      
      $form['species'] = array(
        '#type' => 'select',
        '#title' => t('Species'),
        '#options' => array(
          0 => '---Select a Species---',
          1 => 'Species 1',
          2 => 'Species 2',
          3 => 'Species 3',
        ),
        '#default_value' => 0,
      );
      
      for ($i = 0; $i < 10; $i++) {
        $form['species' . $i] = array(
        '#type' => 'select',
        '#options' => array(
          0 => '---Select a Species---',
          1 => 'Species 1',
          2 => 'Species 2',
          3 => 'Species 3',
        ),
        '#disabled' => false,
        '#default_value' => 0,
      );
}

      $form['keywords'] = array(
        '#type' => 'textfield',
        '#title' => t('Keywords'),
        '#description' => t('Please submit keywords separated by commmas'),
        '#required' => true,
        );
      
      
      $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
        );

    /* This is the convention for adding JS files to your form.
     * Since it is added directly to the form, I would imagine 
     * it is only accessible to this specific form.  
     */
    drupal_add_js(drupal_get_path('module', 'custom_module') . "/custom_module.js");

    /*
     * This is instantiating a user token.  It will be verified
     * in the JS file and they will not be given acess to data 
     * returned by AJAX if their token is invalid (if not logged
     * in).
     */
    global $user;
    $newToken = drupal_get_token("my secret value" . $user->uid);
    drupal_add_js("var myToken='$newToken'", "inline");

    return $form;
}

function custom_module_showCustomModuleForm_validate($form, $form_state){
    
//    This should be fixed to prompt the user with multiple error messages
    
    $primaryAuthor = $form_state['values']['primaryAuthor'];
    $organization = $form_state['values']['organization'];
    $publicationStatus = $form_state['values']['publicationStatus'];
    $year = $form_state['values']['year'];
    $title = $form_state['values']['title'];
    $abstract = $form_state['values']['abstract'];
    $species = $form_state['values']['species'];
    $keywords = $form_state['values']['keywords'];
    
    $empty = 0;
    $blank = '';
    
    if ($primaryAuthor == $empty){
        form_set_error('', 'Please select a primary author.');
    }
    else{
    }
    
    if ($organization == $empty){
        form_set_error('', 'Please select the organization you are affiliated with.');
    }
    else{
    }
    
    if ($publicationStatus == $empty){
        form_set_error('','Please select the publication status of your submission.');
    }
    else{
    }
    
    if ($year == $empty){
        form_set_error('','Please select the year corresponding to your submission.');
    }
    else{
        
    }
    
    if ($title == $blank){
        form_set_error('','Please enter the title of your submission.');
    }
    else{
    }
    
    if ($abstract == $blank){
        form_set_error('','Please enter an abstract for your submission.');
    }
    else{
    }
    
    if ($keywords == $blank){
        form_set_error('','Please include at least one keyword with your submission.');
    }
    else{
        
    }
    
    $speciesArray = array();
    
    for ($i = 0; $i < 10; $i++){
        if ($form_state['values']['species' . $i] != 0){
            array_push($speciesArray, $form_state['values']['species' . $i]);
        }
        else{       
        }
    }
    
    if (count($speciesArray) == $empty){
        form_set_error('','Please select at least one species under study');
    }
    else{
        
    }
    
    $secondaryAuthorArray = Array();
    
    for ($i = 0; $i < 30; $i++){
        if ($form_state['values']['secondaryAuthorForm' . $i] != $empty){
            array_push($secondaryAuthorArray, $form_state['values']['secondaryAuthorForm' . $i]);
        }
        else{
        }
        
        if ($form_state['values']['secondaryAuthorCustomForm' . $i] != $blank)
        {
            array_push($secondaryAuthorArray, $form_state['values']['secondaryAuthorCustomForm' . $i]);
        }
        
        else{
            
        }
    }
    
}

function custom_module_showCustomModuleForm_submit($form, &$form_state) {
    $primaryAuthor = $form_state['values']['primaryAuthor'];
    $organization = $form_state['values']['organization'];
    $publicationStatus = $form_state['values']['publicationStatus'];
    $year = $form_state['values']['year'];
    $title = $form_state['values']['title'];
    $abstract = $form_state['values']['abstract'];
    $species = $form_state['values']['species'];
    $keywords = $form_state['values']['keywords'];
    
    $empty = 0;
    $blank = '';
    
    if ($primaryAuthor == $empty){
        drupal_set_message('Please select a primary author.');
    }
    else{
    }
    
    if ($organization == $empty){
        drupal_set_message('Please select the organization you are affiliated with.');
    }
    else{
    }
    
    if ($publicationStatus == $empty){
        drupal_set_message('Please select the publication status of your submission.');
    }
    else{
    }
    
    if ($year == $empty){
        drupal_set_message('Please select the year corresponding to your submission.');
    }
    else{
        
    }
    
    if ($title == $blank){
        drupal_set_message('Please enter the title of your submission.');
    }
    else{
    }
    
    if ($abstract == $blank){
        drupal_set_message('Please enter an abstract for your submission.');
    }
    else{
    }
    
    if ($keywords == $blank){
        drupal_set_message('Please include at least one keyword with your submission.');
    }
    else{
        
    }
    
    $speciesArray = array();
    
    for ($i = 0; $i < 10; $i++){
        if ($form_state['values']['species' . $i] != 0){
            array_push($speciesArray, $form_state['values']['species' . $i]);
        }
        else{       
        }
    }
    
    if (count($speciesArray) == $empty){
        drupal_set_message('Please select at least one species under study');
    }
    else{
        
    }
    
    $secondaryAuthorArray = Array();
    
    for ($i = 0; $i < 30; $i++){
        if ($form_state['values']['secondaryAuthorForm' . $i] != $empty){
            array_push($secondaryAuthorArray, $form_state['values']['secondaryAuthorForm' . $i]);
        }
        else{
        }
        
        if ($form_state['values']['secondaryAuthorCustomForm' . $i] != $blank)
        {
            array_push($secondaryAuthorArray, $form_state['values']['secondaryAuthorCustomForm' . $i]);
        }
        
        else{
            
        }
    }
   
}