version: "2"
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: false
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  duplication:
    enabled: true
    config:
      languages:
        php:
          patterns:
            - "*.module"
            - "**/*.inc"
            - "**/*.php"
            - "*.install"
        javascript:
          patterns:
            - "**/*.js"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,module,install"
      standard: "Drupal"
  phpmd:
    enabled: true
    checks:
      CleanCode/MissingImport:
        enabled: false
    config:
      file_extensions:
        - php
        - inc
        - module
        - install
      rulesets: "unusedcode,codesize,design,cleancode"
exclude_patterns:
- "docs/"
- "vendor/"
- "tests/"
