language: php

# Add php version so composer doesn't complain
php:
  - 7.1

services:
  - docker

env:
  - DRUPAL_ROOT=/var/www/html

before_script:
  - docker pull statonlab/tripal3

script:
  - docker run -it -d --rm --name tripal -v "$(pwd)":/modules/tpps statonlab/tripal3
  - sleep 60 # We pause here so postgres and apache complete booting up
  - docker exec -it tripal bash -c "cd /modules/ && git clone https://github.com/statonlab/tripal_manage_analyses.git && drush pm-enable -y tripal_manage_analyses"
  - docker exec -it tripal bash -c "cd /modules/ && git clone https://github.com/NAL-i5K/tripal_eutils.git && drush pm-enable -y tripal_eutils"
  - docker exec -it tripal drush pm-enable -y tpps
  - docker exec -it tripal bash -c "cd /modules/tpps && composer install && DRUPAL_ROOT=/var/www/html ./vendor/bin/phpunit"
