<?php

//hook_init
function tpps_init() {

//    drupal_set_message("Hello");
}

function tpps_menu() {

    $items = array();

    $items['master'] = array(
      'title' => 'TPPS Development',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('tpps_master'),
      'access callback' => 'user_access',
      'access arguments' => array('access content'),
      'type' => MENU_NORMAL_ITEM,
    );
    
    $items['testpage'] = array(
      'title' => 'TPPS test page',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('tpps_test_page'),
      'access callback' => 'user_access',
      'access arguments' => array('access content'),
      'type' => MENU_NORMAL_ITEM
    );

    $items['getHello'] = array(
      'page callback' => 'tpps_ajaxCallHandler',
      'access callback' => 'user_access',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK
    );
    
    $items['author/autocomplete'] = array(
      'title' => 'Autocomplete for Authors',
      'page callback' => '_author_autocomplete',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK
    );
    
    $items['organization/autocomplete'] = array(
      'title' => 'Autocomplete for Organizations',
      'page callback' => '_organization_autocomplete',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK
    );
    
    $items['journal/autocomplete'] = array(
      'title' => 'Autocomplete for Publications',
      'page callback' => '_journal_autocomplete',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK
    );
    
    $items['genus/autocomplete'] = array(
      'title' => 'Autocomplete for genus',
      'page callback' => '_genus_autocomplete',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK
    );
    
    $items['species/autocomplete'] = array(
      'title' => 'Autocomplete for species',
      'page callback' => '_species_autocomplete',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK
    );
    
    $items['phenotype/autocomplete'] = array(
      'title' => 'Autocomplete for Phenotype Name',
      'page callback' => '_phenotype_autocomplete',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK
    );
    
    $items['structure/autocomplete'] = array(
      'title' => 'Autocomplete for Ontological terms',
      'page callback' => '_structure_autocomplete',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK
    );
    
    $items['developmental/autocomplete'] = array(
      'title' => 'Autocomplete for Ontological terms',
      'page callback' => '_development_autocomplete',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK
    );
    
    $items['units/autocomplete'] = array(
      'title' => 'Autocomplete for Units',
      'page callback' => '_units_autocomplete',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK
    );

    return $items;
}

function tpps_ajaxCallHandler() {

    global $user;

    if (empty($_GET['token']) || !drupal_valid_token($_GET['token'], 'my secret value' . $user->uid)) {
        return MENU_ACCESS_DENIED;
    }

    echo "Hello, " . filter_xss($_GET['name']) . "!";
}

function tpps_master($form, &$form_state){
    
    global $user;
    if (isset($user->roles[1]) and $user->roles[1] == 'anonymous user'){
        $destination = drupal_get_destination();
        drupal_goto('user/login', array('query' => $destination));
    }
    else{
        $form_state['saved_values']['Hellopage']['primaryAuthor'] = $user->name;
    }
    
    if (!isset($form_state['stage'])){
        $form_state['stage'] = 'Hellopage';
    }
    
    switch ($form_state['stage']){
        case 'Hellopage':
            $page_number = 1;
            $page_desc = 'Author and Species Information';
            break;
        case 'secondPage':
            $page_number = 2;
            $page_desc = 'Experimental Conditions';
            break;
        case 'thirdPage':
            $page_number = 3;
            $page_desc = 'Tree Accession';
            break;
        case 'fourthPage':
            $page_number = 4;
            $page_desc = 'Submit Data';
            break;
        default:
            break;
    }
    
    $form['step'] = array(
      '#type' => 'textfield',
      '#disabled' => TRUE,
      '#default_value' => $form_state['stage'],
      '#prefix' => "<div id='progress'>Page $page_number of 4: $page_desc</div>",
    );
    
    switch ($form_state['stage']){
        case 'Hellopage':
            include_once('page_1.php');
            page_1_create_form($form, $form_state);
            break;
        
        case 'secondPage':
            include_once('page_2.php');
            page_2_create_form($form, $form_state);
            break;
        
        case 'thirdPage':
            include_once('page_3.php');
            page_3_create_form($form, $form_state);
            break;
        
        case 'fourthPage':
            include_once('page_4.php');
            page_4_create_form($form, $form_state);
            break;
        
        default:
            print_r('Invalid form stage.');
            break;
    }
    
    //print_r($form_state['stage']);
    
    drupal_add_js(drupal_get_path('module', 'tpps') . "/tpps.js");
    
    return $form;
}

function tpps_master_validate($form, &$form_state){
    if ($form_state['triggering_element']['#value'] == 'Back'){
        return;
    }
    
    switch ($form_state['stage']){
        case 'Hellopage':
            include_once('page_1.php');
            page_1_validate_form($form, $form_state);
            drupal_add_js(drupal_get_path('module', 'tpps') . "/tpps.js");
            break;
        
        case 'secondPage':
            include_once('page_2.php');
            page_2_validate_form($form, $form_state);
            drupal_add_js(drupal_get_path('module', 'tpps') . "/tpps.js");
            break;
        
        case 'thirdPage':
            include_once('page_3.php');
            page_3_validate_form($form, $form_state);
            drupal_add_js(drupal_get_path('module', 'tpps') . "/tpps.js");
            break;
        
        case 'fourthPage':
            include_once('page_4.php');
            page_4_validate_form($form, $form_state);
            drupal_add_js(drupal_get_path('module', 'tpps') . "/tpps.js");
            break;
        
        default:
            break;
    }
}

function tpps_master_submit($form, &$form_state){
    
    $form_state['saved_values'][$form_state['stage']] = $form_state['values'];
    
    switch ($form_state['stage']){
        case 'Hellopage':
            $form_state['stage'] = 'secondPage';
            break;
            
        case 'secondPage':
            if ($form_state['triggering_element']['#value'] == 'Back'){
                $form_state['stage'] = 'Hellopage';
            }
            else{
                $form_state['stage'] = 'thirdPage';
            }
            break;
            
        case 'thirdPage':
            if ($form_state['triggering_element']['#value'] == 'Back'){
                $form_state['stage'] = 'secondPage';
            }
            else{
                $form_state['stage'] = 'fourthPage';
            }
            break;
            
        case 'fourthPage':
            if ($form_state['triggering_element']['#value'] == 'Back'){
                $form_state['stage'] = 'thirdPage';
            }
            else{
                //submit_all($form, $form_state);
                drupal_goto('<front>');
            }
            break;
        
        default:
            print_r('Invalid form stage');
            break;
    }
    
    if (isset($form_state['saved_values']['form_build_id'])){
        $form_state['values']['form_build_id'] = $form_state['saved_values']['form_build_id'];
    }
    $form_state['saved_values']['form_build_id'] = $form_state['values']['form_build_id'];
    $form_state['rebuild'] = TRUE;
}

function submit_all($form, &$form_state){
    $values = $form_state['saved_values'];
    $firstpage = $values['Hellopage'];
    $secondpage = $values['secondPage'];
    $thirdpage = $values['thirdPage'];
    $fourthpage = $values['fourthPage'];
    
    $primary_author = $firstpage['primaryAuthor'];
    $organization = $firstpage['organization'];
    $publication = $firstpage['publication'];
    $organism = $firstpage['organism'];
    
    $month_options = array(
      0 => '- Select -',
      1 => 'January',
      2 => 'February',
      3 => 'March',
      4 => 'April',
      5 => 'May',
      6 => 'June',
      7 => 'July',
      8 => 'August',
      9 => 'September',
      10 => 'October',
      11 => 'November',
      12 => 'December'
    );
        
    $year_options = array();

    for ($i = 1950; $i <= 2017; $i++) {
        $index = $i - 1949;
        $year_options[$index] = $i;
    }

    $start = $month_options[$secondpage['StartingDate']['month']] . " " . $year_options[$secondpage['StartingDate']['year']];
    $end = $month_options[$secondpage['EndingDate']['month']] . " " . $year_options[$secondpage['EndingDate']['year']];
    
    if ($secondpage['studyLocation']['type'] === '2'){
        $location = $secondpage['studyLocation']['latitude'] . ' Latitude, ' . $secondpage['studyLocation']['longitude'] . ' Longitude';
    }
    else{
        $location = $secondpage['studyLocation']['customLocation']['region'] . ', ' . $secondpage['studyLocation']['customLocation']['country'];
    }
    
    $datatype_options = array(
      0 => '- Select -',
      1 => 'Genotype x Phenotype',
      2 => 'Genotype',
      3 => 'Genotype x Phenotype x Environment',
      4 => 'Phenotype x Environment',
      5 => 'Genotype x Environment'
    );
    $datatype = $datatype_options[$secondpage['dataType']];
    
    $studytype_options = array(
      0 => '- Select -',
      1 => 'Natural Population (Landscape)',
      2 => 'Growth Chamber',
      3 => 'Greenhouse',
      4 => 'Experimental/Common Garden',
      5 => 'Plantation',
    );
    $study_type = $studytype_options[$secondpage['studyType']];
    
    $tree_accession = $thirdpage['tree-accession'];
    
    function create_record_project($title, $description) {
        
        $first_row = TRUE;
        
        $indexed_projects = db_select('chado.project', 'project')
            ->fields('project', array('project_id', 'name'))
            ->orderBy('project_id', 'DESC')
            ->execute();
        
        foreach($indexed_projects as $row){
            if ($first_row){
                $new_project_id = $row->project_id + 1;
                $first_row = FALSE;
            }
            if ($row->name === $title){
                $title .= "$new_project_id";
                break;
            }
        }
        
        $insert_project = db_insert('chado.project')
            ->fields(array(
              'project_id' => $new_project_id,
              'name' => $title,
              'description' => $description
            ))
            ->execute();
        
        return $new_project_id;
    }
    
    function create_record_organization($organization){
        $will_insert = TRUE;
        $first_row = TRUE;
        $existing_organizations = db_select('chado.contact', 'contact')
            ->fields('contact', array('name', 'contact_id'))
            ->orderBy('contact_id', 'DESC')
            ->execute();

        foreach ($existing_organizations as $row){
            if ($first_row){
                $new_contact_id = $row->contact_id + 1;
                $first_row = FALSE;
            }
            if ($row->name === $organization){
                $will_insert = FALSE;
                $new_contact_id = $row->contact_id;
                break;
            }
        }

        if ($will_insert){
            $insert_organization = db_insert('chado.contact')
                ->fields(array(
                  'name' => $organization,
                  'type_id' => '72',
                  'contact_id' => $new_contact_id
                ))
                ->execute();
        }
        
        return $new_contact_id;
    }
    
    function create_record_study($primary_author, $publication){
        $will_insert_primary = TRUE;
        $first_row_primary = TRUE;
        $new_study_id = '1';
        $indexed_authors = db_select('chado.contact', 'contact')
            ->fields('contact', array('name', 'contact_id'))
            ->orderBy('contact_id', 'DESC')
            ->execute();
        
        foreach ($indexed_authors as $row){
            if ($first_row_primary){
                $new_contact_id = $row->contact_id + 1;
                $first_row_primary = FALSE;
            }
            if ($row->name === $primary_author){
                $will_insert_primary = FALSE;
                $study_contact_id = $row->contact_id;
                break;
            }
        }
        
        if ($will_insert_primary){
            $insert_primary_author = db_insert('chado.contact')
                ->fields(array(
                  'name' => $primary_author,
                  'type_id' => '71',
                  'contact_id' => $new_contact_id
                ))
                ->execute();
            $study_contact_id = $new_contact_id;
        }
        
        $will_insert_pub = TRUE;
        $first_row_pub = TRUE;
        $title = $publication['title'];
        $series_name = $publication['journal'];
        $abstract = $publication['abstract'];
        
        switch((string) $publication['status']){
            case '2':
                $publication_year = $publication['yearSubmitted'];
                break;
            case '3':
                $publication_year = $publication['yearInPress'];
                break;
            case '4':
                $publication_year = $publication['yearPublished'];
                break;
            default:
                break;
        }
        
        $indexed_publications = db_select('chado.pub', 'pub')
            ->fields('pub', array('pub_id', 'title', 'series_name'))
            ->orderBy('pub_id', 'DESC')
            ->execute();
        
        foreach($indexed_publications as $row){
            if ($first_row_pub){
                $new_pub_id = $row->pub_id + 1;
                $first_row_pub = FALSE;
            }
            if ($row->title === $title and $row->series_name === $series_name){
                $will_insert_pub = FALSE;
                $study_pub_id = $row->pub_id;
                break;
            }
        }
        
        if ($will_insert_pub){
            $insert_publication = db_insert('chado.pub')
                ->fields(array(
                  'title' => $title,
                  'series_name' => $series_name,
                  'pub_id' => $new_pub_id,
                  'type_id' => '229',
                  'pyear' => $publication_year,
                  'uniquename' => "$primary_author $series_name $title"
                ))
                ->execute();
            $study_pub_id = $new_pub_id;
        }
        
        $indexed_studies = db_select('chado.study', 'study')
            ->fields('study', array('study_id', 'name'))
            ->orderBy('study_id', 'DESC')
            ->execute();
        
        $name = "$primary_author $title";
        $first_row = TRUE;
        
        foreach($indexed_studies as $row){
            if ($first_row){
                $new_study_id = $row->study_id + 1;
                $first_row = FALSE;
            }
            if ($row->name === $name){
                $name .= "-$new_study_id";
            }
        }
        
        $insert_study = db_insert('chado.study')
            ->fields(array(
              'study_id' => $new_study_id,
              'contact_id' => $study_contact_id,
              'pub_id' => $study_pub_id,
              'name' => $name,
              'description' => $abstract
            ))
            ->execute();
        
        return array($study_contact_id, $study_pub_id, $new_study_id);
    }
    
    function create_record_pubauthor($author, $pub_id, $rank){
        $names = explode(' ', $author);
        $first_name = $names[0];
        $last_name = $names[array_pop(array_keys($names))];
        
        $will_insert = TRUE;
        $first_row = TRUE;
        $indexed_pubauthors = db_select('chado.pubauthor', 'pubauthor')
            ->fields('pubauthor', array('pubauthor_id', 'surname', 'givennames'))
            ->orderBy('pubauthor_id', 'DESC')
            ->execute();
        
        foreach ($indexed_pubauthors as $row){
            if ($first_row){
                $pubauthor_id = $row->pubauthor_id + 1;
                $first_row = FALSE;
            }
            if ($row->surname === $last_name and $row->givennames === $first_name){
                $will_insert = FALSE;
                $pubauthor_id = $row->pubauthor_id;
                break;
            }
        }
        
        if ($will_insert){
            $insert_pubauthor = db_insert('chado.pubauthor')
                ->fields(array(
                  'pubauthor_id' => $pubauthor_id,
                  'pub_id' => $pub_id,
                  'rank' => '1',
                  'editor' => 'false',
                  'surname' => $last_name,
                  'givennames' => $first_name,
                ))
                ->execute();
        }
        
        return $pubauthor_id;
    }
    
    function create_record_projectprop($project_id, $info, $info_cvterm_id){
        $first_row = TRUE;
        $rank = '0';
        
        $indexed_projectprop = db_select('chado.projectprop', 'projectprop')
            ->fields('projectprop', array('projectprop_id', 'project_id', 'type_id', 'rank'))
            ->orderBy('projectprop_id', 'DESC')
            ->execute();
        
        foreach($indexed_projectprop as $row){
            if ($first_row){
                $projectprop_id = $row->projectprop_id + 1;
                $first_row = FALSE;
            }
            if ($row->project_id === $project_id and $row->type_id === $info_cvterm_id){
                if ($row->rank >= $rank){
                    $rank = $row->rank + 1;
                }
                break;
            }
        }
        
        db_insert('chado.projectprop')
            ->fields(array(
              'projectprop_id' => $projectprop_id,
              'project_id' => $project_id,
              'type_id' => $info_cvterm_id,
              'value' => $info,
              'rank' => $rank
            ))
            ->execute();
        
        return $projectprop_id;
    }
    
    function create_record_organism($organism){
        $parts = explode(' ', $organism['species']);
        $genus = $parts[0];
        $species = implode(' ', array_slice($parts, 1));
        
        $will_insert = TRUE;
        $first_row = TRUE;
        
        $indexed_organisms = db_select('chado.organism', 'organism')
            ->fields('organism', array('organism_id', 'genus', 'species'))
            ->orderBy('organism_id', 'DESC')
            ->execute();
        
        foreach($indexed_organisms as $row){
            if ($first_row){
                $organism_id = $row->organism_id + 1;
                $first_row = FALSE;
            }
            if ($row->genus === $genus and $row->species === $species){
                $will_insert = FALSE;
                $organism_id = $row->organism_id;
                break;
            }
        }
        
        if ($will_insert){
            $abbreviation = $genus[0] . " $species";
            $fields = array(
              'organism_id' => $organism_id,
              'genus' => $genus,
              'species' => $species,
              'abbreviation' => $abbreviation,
            );
            
            if (preg_match('/var\./', $species)){
                $fields['type_id'] = '22';
            }
            elseif (preg_match('/subsp\./', $species)){
                $fields['type_id'] = '29';
            }
            elseif (preg_match('/ x /', $species)){
                $fields['type_id'] = '56';
            }
            
            $insert_organism = db_insert('chado.organism')
                ->fields($fields)
                ->execute();
        }
        
        return $organism_id;
    }
    
    function create_record_studyprop($study_id, $info, $info_cvterm_id){
        $first_row = TRUE;
        $rank = '0';
        $info_id = '1';
        
        $indexed_items = db_select('chado.studyprop', 'studyprop')
            ->fields('studyprop', array('studyprop_id', 'study_id', 'type_id', 'rank'))
            ->orderBy('studyprop_id', 'DESC')
            ->execute();
        
        foreach ($indexed_items as $row){
            if ($first_row){
                $info_id = $row->studyprop_id + 1;
                $first_row = FALSE;
            }
            if ($row->study_id === $study_id and $row->type_id === $info_cvterm_id){
                if ($row->rank >= $rank){
                    $rank = $row->rank + 1;
                }
                break;
            }
        }

        $insert_info = db_insert('chado.studyprop')
            ->fields(array(
              'studyprop_id' => $info_id,
              'study_id' => $study_id,
              'type_id' => $info_cvterm_id,
              'value' => $info,
              'rank' => $rank
            ))
            ->execute();
        
        return $info_id;
    }
    
    function create_record_stock($organism_id){
        
        $indexed_stocks = db_select('chado.stock', 'stock')
            ->fields('stock', array('stock_id'))
            ->orderBy('stock_id', 'DESC')
            ->execute();
        
        foreach ($indexed_stocks as $row){
            $stock_id = $row->stock_id + 1;
            break;
        }
        
        $unique_name = "$organism_id-$stock_id";
        
        $stock_insert = db_insert('chado.stock')
            ->fields(array(
              'stock_id' => $stock_id,
              'type_id' => '2824',
              'organism_id' => $organism_id,
              'uniquename' => $unique_name
            ))
            ->execute();
        
        return $stock_id;
    }
    
    function create_record_stockprop($stock_id, $info, $info_cvterm_id){
        $first_row = TRUE;
        $rank = '0';
        
        $indexed_items = db_select('chado.stockprop', 'stockprop')
            ->fields('stockprop', array('stockprop_id', 'stock_id', 'type_id', 'rank'))
            ->orderBy('stockprop_id', 'DESC')
            ->execute();
        
        foreach ($indexed_items as $row){
            if ($first_row){
                $stockprop_id = $row->stockprop_id + 1;
                $first_row = FALSE;
            }
            if ($row->stock_id === $stock_id and $row->type_id === $info_cvterm_id){
                if ($row->rank >= $rank){
                    $rank = $row->rank + 1;
                }
                break;
            }
        }

        $insert_info = db_insert('chado.stockprop')
            ->fields(array(
              'stockprop_id' => $stockprop_id,
              'stock_id' => $stock_id,
              'type_id' => $info_cvterm_id,
              'value' => $info,
              'rank' => $rank
            ))
            ->execute();
        
        return $stockprop_id;
    }
    
    function create_record_phenotypeprop($phenotype_id, $info, $info_cvterm_id){
        $first_row = TRUE;
        $rank = '0';
        $phenotypeprop_id = '1';
        
        $indexed_items = db_select('chado.phenotypeprop', 'phenotypeprop')
            ->fields('phenotypeprop', array('phenotypeprop_id', 'phenotype_id', 'type_id', 'rank'))
            ->orderBy('phenotypeprop_id', 'DESC')
            ->execute();
        
        foreach ($indexed_items as $row){
            if ($first_row){
                $phenotypeprop_id = $row->phenotypeprop_id + 1;
                $first_row = FALSE;
            }
            if ($row->phenotype_id === $phenotype_id and $row->type_id === $info_cvterm_id){
                if ($row->rank >= $rank){
                    $rank = $row->rank + 1;
                }
            }
        }

        $insert_info = db_insert('chado.phenotypeprop')
            ->fields(array(
              'phenotypeprop_id' => $phenotypeprop_id,
              'phenotype_id' => $phenotype_id,
              'type_id' => $info_cvterm_id,
              'value' => $info,
              'rank' => $rank
            ))
            ->execute();
        
        
        return $phenotypeprop_id;
    }
    
    function create_record_phenotype($phenotype){
        $name = $phenotype['name'];
        $phenotype_id = '1';
        
        $indexed_phenotypes = db_select('chado.phenotype', 'phenotype')
            ->fields('phenotype', array('phenotype_id'))
            ->orderBy('phenotype_id', 'DESC')
            ->execute();
        
        foreach ($indexed_phenotypes as $row){
            $phenotype_id = $row->phenotype_id + 1;
            break;
        }
        
        $uniquename = "$name-$phenotype_id";
        
        $insert_phenotype = db_insert('chado.phenotype')
            ->fields(array(
              'phenotype_id' => $phenotype_id,
              'uniquename' => $uniquename,
              'name' => $name,
            ))
            ->execute();
        
        if ($phenotype['environment-check'] == '1'){
            $environment = $phenotype['environment'];
            
            $description_id = create_record_phenotypeprop($phenotype_id, $environment['description'], '2834');
            $unit_id = create_record_phenotypeprop($phenotype_id, $environment['units'], '2842');
        }
        else{
            $non_environment = $phenotype['non-environment'];
            $type = $non_environment['type'];
            $structure = $non_environment['structure'];
            $developmental = $non_environment['developmental'];
            
            if ($type === '1'){
                $binary_1 = $non_environment['binary'][1];
                $binary_2 = $non_environment['binary'][2];
                
                $binary_1_id = create_record_phenotypeprop($phenotype_id, $binary_1, '128023');
                $binary_2_id = create_record_phenotypeprop($phenotype_id, $binary_2, '128023');
            }
            elseif ($type === '2'){
                $min = $non_environment['quantitative']['min'];
                $max = $non_environment['quantitative']['max'];
                
                $min_id = create_record_phenotypeprop($phenotype_id, $min, '52214');
                $max_id = create_record_phenotypeprop($phenotype_id, $max, '52213');
            }
            
            $description_id = create_record_phenotypeprop($phenotype_id, $non_environment['description'], '2834');
            $unit_id = create_record_phenotypeprop($phenotype_id, $non_environment['units'], '2842');
            $structure_id = create_record_phenotypeprop($phenotype_id, $structure, '50292');
            $developmental_id = create_record_phenotypeprop($phenotype_id, $developmental, '50292');
            
            if ($non_environment['structure-check'] === '1'){
                $structure_definition = $non_environment['structure-definition'];
                $structure_definition_id = create_record_phenotypeprop($phenotype_id, "$structure Definition: $structure_definition", '50292');
            }
            if ($non_environment['developmental-check'] === '1'){
                $developmental_definition = $non_environment['developmental-definition'];
                $developmental_definition_id = create_record_phenotypeprop($phenotype_id, "$developmental Definition: $developmental_definition", '50292');
            }
        }
        
        return $phenotype_id;
    }
    
    function create_record_project_dbxref($project_id, $accession_number){
        $first_row = TRUE;
        $version = '1';
        
        $indexed_dbxref = db_select('chado.dbxref', 'dbxref')
            ->fields('dbxref', array('accession', 'version', 'dbxref_id'))
            ->orderBy('dbxref_id', 'DESC')
            ->execute();
        
        foreach ($indexed_dbxref as $row){
            if ($first_row){
                $dbxref_id = $row->dbxref_id;
                $first_row = FALSE;
            }
            if ($row->accession === $accession_number){
                $version .= $row->version;
            }
        }
        
        $insert_dbxref = db_insert('chado.dbxref')
            ->fields(array(
              'db_id' => '176',
              'accession' => $accession_number, 
              'version' => $version
            ))
            ->execute();
        
        $indexed_project_dbxref = db_select('chado.project_dbxref', 'project_dbxref')
            ->fields('project_dbxref')
            ->orderBy('project_dbxref_id', 'DESC')
            ->execute();
        
        foreach ($indexed_project_dbxref as $row){
            $project_dbxref_id = $row->project_dbxref_id + 1;
            break;
        }
        
        $insert_project_dbxref = db_insert('chado.project_dbxref')
            ->fields(array(
              'project_dbxref_id' => $project_dbxref_id,
              'dbxref_id' => $dbxref_id,
              'project_id' => $project_id,
              'is_current' => 'true'
            ))
            ->execute();
        
        return $project_dbxref_id;
    }
    
    $project_id = create_record_project($publication['title'], $publication['abstract']);
    
    $organization_id = create_record_organization($firstpage['organization']);
    
    $study_ids = create_record_study($primary_author, $publication);
    $study_contact_id = $study_ids[0];
    $study_pub_id = $study_ids[1];
    $study_id = $study_ids[2];
    
    $primary_pubauthor_id = create_record_pubauthor($primary_author, $study_pub_id, '1');
    
    $options = array(
      0 => t('- Select -'),
      2 => t('In Preparation or Submitted'),
      3 => t('In press'),
      4 => t('Published'),
    );
    $status = $options[$publication['status']];
    
    $pub_status_id = create_record_projectprop($project_id, $status, '52310');
    
    $secondaryAuthors_id = array();
    if ($publication['secondaryAuthors']['check'] == '0' and $publication['secondaryAuthors']['number'] != '0'){
        for($i = 1; $i <= $publication['secondaryAuthors']['number']; $i++){
            $secondaryAuthors_id[$i] = create_record_pubauthor($publication['secondaryAuthors'][$i], $study_pub_id, $i + 1);
        }
    }
    elseif ($publication['secondaryAuthors']['check'] == '0'){
        create_record_projectprop($project_id, file_create_url(file_load($publication['secondaryAuthors']['file'])->uri), '128024');
    }
    
    $organism_id = array();
    for ($i = 1; $i <= $organism['number']; $i++){
        $organism_id[$i] = create_record_organism($organism["$i"]);
    }
    
    $start_date_id = create_record_studyprop($study_id, $start, '127996');
    $end_date_id = create_record_studyprop($study_id, $end, '127997');
    $experiment_location_id = create_record_studyprop($study_id, $location, '127998');
    $datatype_id = create_record_studyprop($study_id, $datatype, '54740');//need jill's confirmation on cvterm_id for 'association_results_type'
    $study_type_id = create_record_studyprop($study_id, $study_type, '128021');
    
    if ($secondpage['studyType'] == '1'){
        $natural_population = $secondpage['naturalPoplulation'];
        $number_assessions = $natural_population['assession'];
        $seasons = "";
        foreach ($natural_population['season'] as $key => $item){
            if ($item == '1'){
                $season .= $key . ', ';
            }
        }
        $season_id = create_record_studyprop($study_id, $seasons, '128000');
        $assessions_id = create_record_studyprop($study_id, $number_assessions, '128001');
    }
    elseif ($secondpage['studyType'] == '2'){
        $growth_chamber = $secondpage['growthChamber'];
        $co2 = $growth_chamber['co2Control'];
        $humidity = $growth_chamber['humidityControl'];
        $light = $growth_chamber['lightControl'];
        $temp_high = $growth_chamber['temp']['high'];
        $temp_low = $growth_chamber['temp']['low'];
        $rooting = $growth_chamber['rooting'];
        $rooting_type = $rooting['option'];
        $soil = $rooting['soil'];
        $soil_container = $soil['container'];
        $ph = $rooting['ph'];
        $treatments = $rooting['treatment'];
        
        if ($co2['option'] == '1'){
            $co2_control_id = create_record_studyprop($study_id, 'True', '128002');
            $co2_value_id = create_record_studyprop($study_id, $co2['controlled'], '128003');
        }
        else{
            $co2_control_id = create_record_studyprop($study_id, 'False', '128002');
            $co2_value_id = create_record_studyprop($study_id, $co2['uncontrolled'], '128003');
        }
        
        if ($humidity['option'] == '1'){
            $humidity_control_id = create_record_studyprop($study_id, 'True', '128004');
            $humidity_value_id = create_record_studyprop($study_id, $humidity['controlled'], '128005');
        }
        else{
            $humidity_control_id = create_record_studyprop($study_id, 'False', '128004');
            $humidity_value_id = create_record_studyprop($study_id, $humidity['uncontrolled'], '128005');
        }
        
        if ($light['option'] == '1'){
            $light_control_id = create_record_studyprop($study_id, 'True', '128006');
            $light_value_id = create_record_studyprop($study_id, $light['controlled'], '128007');
        }
        else{
            $light_control_id = create_record_studyprop($study_id, 'False', '128006');
            $light_value_id = create_record_studyprop($study_id, $light['uncontrolled'], '128007');
        }
        
        $temp_high_id = create_record_studyprop($study_id, $temp_high, '128008');
        $temp_low_id = create_record_studyprop($study_id, $temp_low, '128009');
        
        switch((string) $rooting_type){
            case '1':
                $rooting_type_id = create_record_studyprop($study_id, 'Aeroponics', '128010');
                break;
            case '2':
                $rooting_type_id = create_record_studyprop($study_id, 'Hydroponics', '128010');
                break;
            case '3':
                $rooting_type_id = create_record_studyprop($study_id, 'Soil', '128010');
                $soil_options = array(
                  0 => '- Select -',
                  1 => 'Sand',
                  2 => 'Peat',
                  3 => 'Clay',
                  4 => 'Mixed',
                  5 => 'Other'
                );
                $soil_type = $soil_options[$soil['type']];
                if ($soil_type == 'Other'){
                    $soil_type = $soil['other'];
                }

                $soil_type_id = create_record_studyprop($study_id, $soil_type, '128011');
                $soil_container_id = create_record_studyprop($study_id, $soil_container, '128012');
                break;
            default:
                break;
        }
        
        if ($ph['option'] == '1'){
            $ph_control_id = create_record_studyprop($study_id, 'True', '128013');
            $ph_value_id = create_record_studyprop($study_id, $ph['controlled'], '128014');
        }
        else{
            $ph_control_id = create_record_studyprop($study_id, 'False', '128013');
            $ph_value_id = create_record_studyprop($study_id, $ph['uncontrolled'], '128014');
        }
        
        $treatment_id = array();
        $is_description = FALSE;
        foreach ($treatments as $item){
            if (!$is_description){
                if ($item == '1'){
                    $record_next = TRUE;
                }
                else{
                    $record_next = FALSE;
                }
                $is_description = TRUE;
            }
            else{
                if ($record_next){
                    array_push($treatment_id, create_record_studyprop($study_id, $item, '128015'));
                }
                $is_description = FALSE;
            }
        }
    }
    elseif ($secondpage['studyType'] == '3'){
        $greenhouse = $secondpage['greenhouse'];
        $humidity = $greenhouse['humidityControl'];
        $light = $greenhouse['lightControl'];
        $temp_high = $greenhouse['temp']['high'];
        $temp_low = $greenhouse['temp']['low'];
        $rooting = $greenhouse['rooting'];
        $rooting_type = $rooting['option'];
        $soil = $rooting['soil'];
        $soil_container = $soil['container'];
        $ph = $rooting['ph'];
        $treatments = $rooting['treatment'];
        
        if ($humidity['option'] == '1'){
            $humidity_control_id = create_record_studyprop($study_id, 'True', '128004');
            $humidity_value_id = create_record_studyprop($study_id, $humidity['controlled'], '128005');
        }
        else{
            $humidity_control_id = create_record_studyprop($study_id, 'False', '128004');
        }
        
        if ($light['option'] == '1'){
            $light_control_id = create_record_studyprop($study_id, 'True', '128006');
            $light_value_id = create_record_studyprop($study_id, $light['controlled'], '128007');
        }
        else{
            $light_control_id = create_record_studyprop($study_id, 'False', '128006');
        }
        
        $temp_high_id = create_record_studyprop($study_id, $temp_high, '128008');
        $temp_low_id = create_record_studyprop($study_id, $temp_low, '128009');
        
        switch((string) $rooting_type){
            case '1':
                $rooting_type_id = create_record_studyprop($study_id, 'Aeroponics', '128010');
                break;
            case '2':
                $rooting_type_id = create_record_studyprop($study_id, 'Hydroponics', '128010');
                break;
            case '3':
                $rooting_type_id = create_record_studyprop($study_id, 'Soil', '128010');
                $soil_options = array(
                  0 => '- Select -',
                  1 => 'Sand',
                  2 => 'Peat',
                  3 => 'Clay',
                  4 => 'Mixed',
                  5 => 'Other'
                );
                $soil_type = $soil_options[$soil['type']];
                if ($soil_type == 'Other'){
                    $soil_type = $soil['other'];
                }

                $soil_type_id = create_record_studyprop($study_id, $soil_type, '128011');
                $soil_container_id = create_record_studyprop($study_id, $soil_container, '128012');
                break;
            default:
                break;
        }
        
        if ($ph['option'] == '1'){
            $ph_control_id = create_record_studyprop($study_id, 'True', '128013');
            $ph_value_id = create_record_studyprop($study_id, $ph['controlled'], '128014');
        }
        else{
            $ph_control_id = create_record_studyprop($study_id, 'False', '128013');
        }
        
        $treatment_id = array();
        $is_description = FALSE;
        foreach ($treatments as $item){
            if (!$is_description){
                if ($item == '1'){
                    $record_next = TRUE;
                }
                else{
                    $record_next = FALSE;
                }
                $is_description = TRUE;
            }
            else{
                if ($record_next){
                    array_push($treatment_id, create_record_studyprop($study_id, $item, '128015'));
                }
                $is_description = FALSE;
            }
        }
        
    }
    elseif ($secondpage['studyType'] == '4'){
        $commonGarden = $secondpage['commonGarden'];
        $salinity = $commonGarden['salinity'];
        $biotic_env = $commonGarden['bioticEnv']['option'];
        $seasons = "";
        $treatments = $commonGarden['treatment'];
        
        $irrigation_options = array(
          0 => '- Select -',
          1 => 'Irrigation from top',
          2 => 'Irrigation from bottom',
          3 => 'Drip Irrigation',
          4 => 'Other',
          5 => 'No Irrigation',
        );
        $irrigation_type = $irrigation_options[$commonGarden['irrigation']['option']];
        if ($irrigation_type == 'Other'){
            $irrigation_type = $commonGarden['irrigation']['other'];
        }
        
        $irrigation_type_id = create_record_studyprop($study_id, $irrigation_type, '128016');
        
        if ($salinity['option'] == '1'){
            $salinity_control_id = create_record_studyprop($study_id, 'True', '128017');
            $salinity_value_id = create_record_studyprop($study_id, $salinity['controlled'], '128018');
        }
        else{
            $salinity_control_id = create_record_studyprop($study_id, 'False', '128017');
            $salinity_value_id = create_record_studyprop($study_id, $salinity['uncontrolled'], '128018');
        }
        
        $biotic_env['Other'] = $commonGarden['bioticEnv']['other'];
        $biotic_env_id = array();
        foreach ($biotic_env as $key => $check){
            if ($check == '1'){
                $biotic_env_id[$key] = create_record_studyprop($study_id, $key, '128019');
            }
        }
        
        foreach ($commonGarden['season'] as $key => $item){
            if ($item == '1'){
                $season .= $key . ', ';
            }
        }
        $season_id = create_record_studyprop($study_id, $seasons, '128000');
        
        $treatment_id = array();
        $is_description = FALSE;
        foreach ($treatments as $item){
            if (!$is_description){
                if ($item == '1'){
                    $record_next = TRUE;
                }
                else{
                    $record_next = FALSE;
                }
                $is_description = TRUE;
            }
            else{
                if ($record_next){
                    array_push($treatment_id, create_record_studyprop($study_id, $item, '128015'));
                }
                $is_description = FALSE;
            }
        }
    }
    elseif ($secondpage['studyType'] == '5'){
        $plantation = $secondpage['plantation'];
        $number_assessions = $plantation['assession'];
        $seasons = "";
        foreach ($plantation['season'] as $key => $item){
            if ($item == '1'){
                $season .= $key . ', ';
            }
        }
        $season_id = create_record_studyprop($study_id, $seasons, '128000');
        $assessions_id = create_record_studyprop($study_id, $number_assessions, '1280001');
    }
    
    $tree_accession_path = file_create_url(file_load($tree_accession)->uri);
    
    for ($i = 1; $i <= $organism['number']; $i++){
        $phenotype = $fourthpage["organism-$i"]['phenotype'];
        $phenotype_number = $phenotype['number'];
        $genotype = $fourthpage["organism-$i"]['genotype'];
        $bioproject = $genotype['BioProject-id'];
        $assembly_file = $genotype['assembly'];
        $snps_file = $genotype['SNPs'];
        
        $stock_id = create_record_stock($organism_id[$i]);
        $tree_accession_id = create_record_stockprop($stock_id, $tree_accession_path, '128024');
        
        if ($phenotype['check'] === '1'){
            $file_path = file_create_url(file_load($phenotype['file'])->uri);
            
            $indexed_phenotypes = db_select('chado.phenotype', 'phenotype')
                ->fields('phenotype', array('phenotype_id'))
                ->orderBy('phenotype_id', 'DESC')
                ->execute();

            foreach ($indexed_phenotypes as $row){
                $phenotype_id = $row->phenotype_id + 1;
                break;
            }

            $uniquename = "PHENOTYPE-FILE-PATH-$phenotype_id";

            $insert_phenotype = db_insert('chado.phenotype')
                ->fields(array(
                  'phenotype_id' => $phenotype_id,
                  'uniquename' => $uniquename,
                  'value' => $file_path,
                ))
                ->execute();
        }
        else{
            $phenotype_id = array();
            for ($j = 1; $j <= $phenotype_number; $j++){
                $current_phenotype = $phenotype["$j"];
                $phenotype_id[$j] = create_record_phenotype($current_phenotype);
            }
        }
        
        $bioproject_id = create_record_project_dbxref($project_id, $bioproject);
        $assembly_id = create_record_projectprop($project_id, file_create_url(file_load($assembly_file)->uri), '128024');
        $snps_id = create_record_projectprop($project_id, file_create_url(file_load($snps_file)->uri), '128024');
    }
}

function _author_autocomplete($string){
    $matches = array();
    $result = db_select('chado.contact', 'contact')
        ->fields('contact', array('name', 'type_id'))
        ->condition('name', db_like($string) . '%', 'LIKE')
        ->condition('type_id', '71', 'LIKE')
        ->execute();
    
    foreach($result as $row){
        $matches[$row->name] = check_plain($row->name);
    }
    
    drupal_json_output($matches);
}

function _organization_autocomplete($string){
    $matches = array();
    $result = db_select('chado.contact', 'contact')
        ->fields('contact', array('name', 'type_id'))
        ->condition('name', db_like($string) . '%', 'LIKE')
        ->condition('type_id', '72', 'LIKE')
        ->execute();
    
    foreach($result as $row){
        $matches[$row->name] = check_plain($row->name);
    }
    
    drupal_json_output($matches);
}

function _journal_autocomplete($string){
    $matches = array();
    $result = db_select('chado.pub', 'pub')
        ->fields('pub', array('series_name'))
        ->condition('series_name', db_like($string) . '%', 'LIKE')
        ->execute();
    
    foreach($result as $row){
        $matches[$row->series_name] = check_plain($row->series_name);
    }
    
    drupal_json_output($matches);
}

function _species_autocomplete($string){
    $matches = array();
    
    $parts = explode(" ", $string);
    if (!isset($parts[1])){
        $parts[1] = "";
    }
    //var_dump($parts);
    
    $result = db_select('chado.organism', 'organism')
        ->fields('organism', array('genus', 'species'))
        ->condition('genus', db_like($parts[0]) . '%', 'LIKE')
        ->condition('species', db_like($parts[1]) . '%', 'LIKE')
        ->orderBy('genus')
        ->orderBy('species')
        ->execute();
    
    foreach($result as $row){
        $matches[$row->genus . " " . $row->species] = check_plain($row->genus . " " . $row->species);
    }
    
    drupal_json_output($matches);
}

function _phenotype_autocomplete($string){
    $matches = array();
    
    $result = db_select('chado.phenotype', 'phenotype')
        ->fields('phenotype', array('name'))
        ->condition('name', db_like($string) . '%', 'LIKE')
        ->execute();
    
    foreach($result as $row){
        $matches[$row->name] = check_plain($row->name);
    }
    
    drupal_json_output($matches);
}

function _structure_autocomplete($string){
    $matches = array();
    $result = db_select('chado.phenotype_structure_cvterm', 'phenotype_structure_cvterm')
        ->fields('phenotype_structure_cvterm', array('name', 'definition'))
        ->condition('name', db_like($string) . '%', 'LIKE')
        ->execute();
    
    foreach($result as $row){
        if ($row->definition != ""){
            $matches[$row->name] = check_plain($row->name . ":  " . $row->definition);
        }
        else{
            $matches[$row->name] = check_plain($row->name . ":  No definition on record");
        }
    }
    
    drupal_json_output($matches);
}

function _development_autocomplete($string){
    $matches = array();
    $result = db_select('chado.phenotype_cvterm', 'phenotype_cvterm')
        ->fields('phenotype_cvterm', array('name', 'definition'))
        ->condition('name', db_like($string) . '%', 'LIKE')
        ->execute();
    
    foreach($result as $row){
        if ($row->definition != ""){
            $matches[$row->name] = check_plain($row->name . ":  " . $row->definition);
        }
        else{
            $matches[$row->name] = check_plain($row->name . ":  No definition on record");
        }
    }
    
    drupal_json_output($matches);
}

function parse_xlsx($location){
    
    //modified from https://gist.github.com/searbe/3284011
    
    $content = array();
    $dir = '/var/www/Drupal/sites/default/files';
    
    $zip = new ZipArchive();
    $zip->open($location);
    $zip->extractTo($dir);

    $strings = simplexml_load_file($dir . '/xl/sharedStrings.xml');
    $sheet = simplexml_load_file($dir . '/xl/worksheets/sheet1.xml');

    $xlrows = $sheet->sheetData->row;

    foreach ($xlrows as $xlrow) {
        $arr = array();
        
        foreach ($xlrow->c as $cell) {
            
            $v = (string) $cell->v;

            if (isset($cell['t']) && $cell['t'] == 's') {
                $s  = array();
                $si = $strings->si[(int) $v];
                $si->registerXPathNamespace('n', 'http://schemas.openxmlformats.org/spreadsheetml/2006/main');
                
                foreach($si->xpath('.//n:t') as $t) {
                    $s[] = (string) $t;
                }
                
                $v = implode($s);
            }
            $arr[] = $v;
        }

        if (!isset($headers)) {
            $headers = $arr;
            $content['headers'] = $headers;
        } 
        else{
            $values = array_pad($arr, count($headers), '');
            $row    = array_combine($headers, $values);
            $content[] = $row;
        }
    }
    
    @unlink($dir);
    @unlink($inputFile);
    
    return $content;
    
}

function tpps_test_page($form, &$form_state){
    include_once  'test_page.php';
    
    $form = test_page_create_form($form, $form_state);
    
    return $form;
}

function tpps_test_page_validate($form, &$form_state){
    include_once 'test_page.php';
    
    test_page_validate_form($form, $form_state);
}

function tpps_test_page_submit($form, &$form_state) {
    include_once 'test_page.php';
    
    test_page_submit_form($form, $form_state);
}
