<?php

/**
 * @file
 * Defines module schema and install/uninstall processes.
 */

/**
 * Implements hook_uninstall().
 */
function custom_blocks_uninstall() {
  db_delete('block')
    ->condition('module', 'custom_blocks')
    ->execute();
  cache_clear_all('*', 'cache_block', TRUE);
}

/**
 * Implements hook_install().
 */
function custom_blocks_install() {
  // Force block discovery and update the block table.
  // Note: works only for current theme.
  _block_rehash();

  // Flag which indicates if cache must be cleared after any block's update.
  $cache_must_be_cleared = FALSE;
  $module_name = 'custom_blocks';

  // Place blocks listed below into theme's region.
  $delta_list = [
    'featured_treegenes_resources',
    'publication_details_page_title',
  ];

  module_load_include('module', 'custom_blocks');
  $block_meta = custom_blocks_block_info();

  $theme_name = 'dawn';
  foreach ($delta_list as $delta) {
    if (empty($block_meta[$delta]['properties'])) {
      continue;
    }
    $block = custom_blocks_block_view($delta);
    unset($block_meta[$delta]['properties']['administrative']);
    $fields = array_merge(
      $block_meta[$delta]['properties'],
      // Get block title for end users.
      [
        'title' => ($block['subject'] ?? $block_meta[$delta]['info']),
        'module' => $module_name,
        'delta' => $delta,
        'theme' => $theme_name,
      ]
    );

    $num_updated = db_update('block')
      ->fields($fields)
      ->condition('module', $module_name)
      ->condition('delta', $delta)
      ->condition('theme', $theme_name)
      ->execute();

    if ($num_updated) {
      drupal_set_message(t(
        'Block "@delta" has been placed in the Content region.',
        ['@delta' => $delta]
      ));
    }
    else {
      $num_updated = db_insert('block')
        ->fields($fields)
        ->execute();
    }
  }
  cache_clear_all('*', 'cache_block', TRUE);

  // Remove blocks by id.
  $bid_list = [17, 16, 25, 28];
  //custom_blocks_remove($bid_list);
}
