<?php

/**
 * @file
 * Main file for 'custom_blocks'.
 */

/**
 * Implements hook_block_info().
 */
function custom_blocks_block_info() {
  $blocks['featured_treegenes_resources'] = [
    'info' => t('Featured TreeGenes Resources'),
    'cache' => DRUPAL_CACHE_GLOBAL,
    // 'Properties' doesn't work on module installation.
    'properties' => [
      'administrative' => FALSE,
      'weight' => 0,
      // Enable by default.
      'status' => 1,
      // Place in Content region.
      'region' => 'content',
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    ],
  ];

  return $blocks;
}

/**
 * This hook generates the contents of the blocks.
 */
function custom_blocks_block_view($delta = '') {
  $block = [];
  switch ($delta) {
    case 'featured_treegenes_resources':
      $block['subject'] = t('Featured TreeGenes Resources');
      $block['content'] = custom_block_get_16_body();
      break;

  }
  return $block;
}

/**
 * Builds content of the block #16 ('Featured TreeGenes Resources'.
 *
 * @return string
 *   Returns rendered HTML-table.
 */
function custom_block_get_16_body() {
  $rows = [
    [
      //'<div class="card">
      //  <img typeof="foaf:Image" class="img-responsive" src="' . url('sites/default/files/uploads/galaxy-ss.jpg') . '" />
      //  <h3 class="thumb-title">' . l(t('Galaxy'), 'http://treegenes.cam.uchc.edu/') . '</h3>
      //</div>',
      '<div class="card">
        <img typeof="foaf:Image" class="img-responsive"
          src="' . url('sites/default/files/uploads/ctree.png') . '" />
        <h3 class="thumb-title">' . l(t('CartograPlant'), 'https://treegenesdb.org/cartograplant') . '</h3>
      </div>',
      '<div class="card">
        <img typeof="foaf:Image" class="img-responsive" src="' . url('sites/default/files/uploads/jbrowse-ss.jpg') . '" />
        <h3 class="thumb-title">' . l(t('JBrowse'), 'jbrowse') . '</h3>
      </div>',
    ],
  ];
  $output = theme('table', [
    'rows' => $rows,
    'attributes' => [
      'id' => 'featured-treegenes-resources',
    ],
  ]);
  drupal_add_css(drupal_get_path('module', 'custom_blocks') . '/custom_blocks.css');
  return $output;
}
