<?php

/**
 * @file
 * Main file for 'cmap' module.
 */

/**
 * Implements hook_permission().
 */
function cmap_permission() {
  return [
    'administer cmap' => [
      'title' => t('Administer "cmap" module'),
      'description' => t('Allows to change all settings.'),
    ],
  ];
}

/**
 * Implements hook_menu().
 */
function cmap_menu() {
  $items = [];
  // Settings Page.
  $items['admin/config/cmap'] = [
    'title' => 'CMAP',
    'description' => 'CMAP Page Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['cmap_settings_form'],
    'access arguments' => ['administer cmap'],
    'type' => MENU_NORMAL_ITEM,
    'file' => 'cmap.admin.inc',
    'weight' => -100,
  ];
  $cmap_path = variable_get('cmap_path', 'cmap2');
  $items[$cmap_path] = [
    'title' => 'Treegenes Comparative Map Viewer',
    // Block's description: summary of cmaps.
    'page callback' => 'drupal_get_form',
    'page arguments' => ['cmap_form'],
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  ];
  return $items;
}

/**
 * Form callback. Builds CMAP page content including search form.
 */
function cmap_form(array $form, array &$form_state) {
  $form['content'] = [
    '#markup' => cmap_build_content(),
  ];

  $css = [
    'type' => 'file',
    'data' => drupal_get_path('module', 'cmap') . '/cmap.css',
  ];
  $form['#attached'] = ['css' => [$css]];

  return $form;
}

/**
 * Original content of the block #17.
 *
 * Block's settings page:
 * /admin/structure/block/manage/block/17/configure.
 *
 * Title: Treegenes Comparative Map Viewer
 * Desctiption: summary of cmaps
 * Restrictions:
 * - Block is shown only at /cmap page.
 * - No other restrictions.
 */
function cmap_build_content() {
  $output = '
    <h2 style="font-size: 18px; padding-bottom: 10px;margin-bottom: 10px;">CMAP Overview</h2>
    <p>
    The TreeGenes CMAP repository hosts <strong>100</strong> genetic map sets for <strong>34</strong> unique species. These maps are connected to species and publication records, as well as supporting Genbank Bioprojects when available.  Map sets contain a variety of marker types including RAPDs, AFLPs, SSRs, ESTs, and SNPs.  Users may browse these maps, download the data directly, and submit their own map data <strong><a href="TG_Map/Upload">here</a></strong>.
    </p>';

  if (isset($_GET["id"])) {
    $filterID = filter_xss(htmlspecialchars($_GET["id"]));
  }
  else {
    $filterID = "";
  }

  $query = "select
      distinct tg.genus,
      tg.species,
      tg.organism_id
    from chado.tg_code tg
    inner join cmap_map_set
      on tg.organism_id=cmap_map_set.species_id
    order by tg.genus";
  $speciesListDB = db_query($query);

  // Iterate through the returned database.
  for($i = 0; $i < $speciesListDB->rowCount(); $i++) {
    $speciesList[$i] = $speciesListDB->fetchAssoc();
  }

  $output .= '
    <form class="filterForm" id="filterCmapList" method="get" action="">
    <select name="id" value="512">';

  foreach ($speciesList as $species) {
    // Truncate any ridiculously long names (species).
    if (strlen($species['species']) > 80) {
      $species['species'] = substr($species['species'], 0, 80). "...";
    }
    // echo "<option value=\"$species['organism_id']\">$species['genus'] $species['species']</option>";
    if ($filterID == $species['organism_id']) {
      $output .= "<option selected=\"selected\" name=\""
        . $species['organism_id'] . "\" value=\"" . $species['organism_id']
        . "\">" . $species['genus'] . " " . $species['species'] . "</option>";
    }
    else {
      $output .= "<option name=\"" . $species['organism_id'] . "\" value=\""
        . $species['organism_id'] . "\">".$species['genus'] . " " . $species['species']."</option>";
    }
  }

  $output .= "</select>"
    . "<input type=\"submit\" value=\"Filter this list\"></form>"
    . "<form class=\"resetForm\"><input type=\"submit\" value=\"Reset\"></form><br />";
  // Get the map data.
  if ($filterID == "") {
    $query = "select
        map_set_id,
        map_set_name,
        map_set_short_name,
        map_set_acc,
        tg.genus,
        tg.species,
        map_type_acc,
        published_on,
        mapping_population
     from cmap_map_set
     inner join chado.tg_code tg
       on cmap_map_set.species_id=tg.organism_id
     order by map_set_id";
  }
  else {
    $query = "select
        map_set_id,
        map_set_name,
        map_set_short_name,
        map_set_acc,
        tg.genus,
        tg.species,
        map_type_acc,
        published_on,
        mapping_population
      from cmap_map_set
      inner join chado.tg_code tg
        on cmap_map_set.species_id=tg.organism_id
        and tg.organism_id='$filterID'
      order by map_set_id";
  }
  $map_set_details_list = db_query($query);
  for ($i = 0; $i < $map_set_details_list->rowCount(); $i++) {
    $map_set_details[$i] = $map_set_details_list->fetchAssoc();
  }
  // Get linkage group count (no need to filter by ID since we can do
  // this later without a multiple join SQL query).
  $query = "select
      map_set_id,
      count(map_set_id) as count
    from cmap_map
    group by map_set_id
    order by map_set_id";

  $linkageGroupCount = db_query($query);
  for ($i = 0; $i < $linkageGroupCount->rowCount(); $i++) {
    $linkageGroupCountList[$i] = $linkageGroupCount->fetchAssoc();
  }


  // Get the map sets and maps available.
  $query = "select
      s.map_set_name,
      s.map_set_id,
      m.map_name
    from cmap_map_set s
    join cmap_map m
      on m.map_set_id=s.map_set_id
    order by m.map_name";
  $mapsAvailable = db_query($query);
  for ($i = 0; $i < $mapsAvailable->rowCount(); $i++) {
    $mapsAvailableList[$i] = $mapsAvailable->fetchAssoc();
  }

  // @TODO Review code below.
  //

  // Get the Publication ID (chado.pub).
  // $query = "select map_set_id, cpub.pub_id, cpub.title
  // from cmap_map_set_pub inner
  // join chado.pub cpub on cmap_map_set_pub.pub_id=cpub.pub_id
  // order by map_set_id";
  $query = "select
      map_set_id,
      cpub.pub_id,
      cpub.title,
      cbd13.entity_id
    from cmap_map_set_pub
    inner join chado.pub cpub
      on cmap_map_set_pub.pub_id=cpub.pub_id
    LEFT JOIN public.chado_bio_data_13 as cbd13
      ON cpub.pub_id = cbd13.record_id
    order by map_set_id";

  $publications = db_query($query);
  for ($i = 0; $i < $publications->rowCount(); $i++) {
    $publicationsList[$i] = $publications->fetchAssoc();
  }

  // Get the bioproject accession links.
  $query = "select
      dx.dbxref_id,
      dx.accession,
      p.project_id,
      c.cmap_map_set_id
    from chado.dbxref dx
    join chado.project_dbxref p
      on dx.dbxref_id = p.dbxref_id
    join cmap_map_set_dbxref c
      on c.dbxref_id=dx.dbxref_id";

  $bioProjects = db_query($query);
  for ($i = 0; $i < $bioProjects->rowCount(); $i++) {
    $bioProjectsList[$i] = $bioProjects->fetchAssoc();
  }

  // Display some basic info.
  for ($i = 0; $i < count($map_set_details); $i++) {
    // Prepare map_set_name for human-readability.
    $studyName = explode('_', $map_set_details[$i]['map_set_name']);
    $linkageGroupIndex = cmap_get_link_group_count(
      $map_set_details[$i]['map_set_id'],
      $linkageGroupCountList
    );
    $output .= "<div id=\"" . $map_set_details[$i]['map_set_id']
      . "box\" class=\"speciesBox\">"
      . "<h4>" . $map_set_details[$i]['genus'] . " "
      . $map_set_details[$i]['species'] . ": " . $studyName[4]
      . " (" . $studyName[3] . ", " . $studyName[1] . ")</h4>"
    // "<h4>".$map_set_details[$i]['map_set_name']."</h4>"
    . "<table class=\"studyTable\">"
    . "<tr><td class=\"keyTD\">Abbreviated name:</td><td class=\"valueTD\">"
      . $map_set_details[$i]['map_set_short_name'] . "</td></tr>"
    . "<tr><td class=\"keyTD\">Accession:</td><td class=\"valueTD\">"
      . $map_set_details[$i]['map_set_acc'] . "</td></tr>"
    //TODO - make sure species page exists before linking to it (all should be
    // on site though if we have maps for them)
    . "<tr><td class=\"keyTD\">Species:</td><td class=\"valueTD\"><a
      href=\"organism/" . $map_set_details[$i]['genus'] . "-"
      . $map_set_details[$i]['species'] . "\">"
      . $map_set_details[$i]['genus'] . " " . $map_set_details[$i]['species']
      . "</a></td></tr>"
    . "<tr><td class=\"keyTD\">Linkage groups:</td><td class=\"valueTD\">"
      . $linkageGroupCountList[$linkageGroupIndex]['count'] . "</td></tr>"
    . "<tr><td class=\"keyTD\">Published on:</td><td class=\"valueTD\">"
      . $map_set_details[$i]['published_on'] . "</td></tr>"
    . "<tr><td class=\"keyTD\">Mapping Population:</td><td class=\"valueTD\">"
      . $map_set_details[$i]['mapping_population'] . "</td></tr>";
    // Publication.
    for ($k = 0; $k < count($publicationsList); $k++) {
      if ($map_set_details[$i]['map_set_id'] == $publicationsList[$k]['map_set_id']) {
        $output .= "<tr><td class=\"keyTD\">Publication:</td><td
          class=\"valueTD\"><a href=\"/Publication/"
          . $publicationsList[$k]['entity_id'] . "\">"
          . $publicationsList[$k]['title'] . "</a></td></tr>";
        // echo "<tr><td>Publication:</td><td>Link</td></tr>";
      }
    }

    // Bioproject.
    for ($k = 0; $k < count($bioProjectsList); $k++) {
      if ($map_set_details[$i]['map_set_id'] == $bioProjectsList[$k]['cmap_map_set_id']) {
        $output .= "<tr><td class=\"keyTD\">Bioproject:</td><td
          class=\"valueTD\"><a href=\"https://www.ncbi.nlm.nih.gov/bioproject/"
          . $bioProjectsList[$k]['accession'] . "\">NCBI BioProject:"
          . $bioProjectsList[$k]['accession'] . "</a></td></tr>";
      }
    }

    $output .= "</table>";
    $output .= "<br/>";

    // List the maps available.
    $output .= "<table class=\"mapsAvailableTable\">";
    for ($j = 0; $j < count($mapsAvailableList); $j++) {
      if ($map_set_details[$i]['map_set_id'] == $mapsAvailableList[$j]['map_set_id']) {
        $output .= "<tr>";
        $output .= "<td class=\"keyTD\">" . $mapsAvailableList[$j]['map_name'] . "</td>";
        $output .= "<td><a href=\"/cmap-js/index.html?config=tg/tg.php?mapinfo="
          . $mapsAvailableList[$j]['map_name'] . "__CMAP__"
          . $mapsAvailableList[$j]['map_set_name'] . "\">Map Viewer</a></td>";
        $output .= "</tr>";
      }
    }
    $output .= "</table>";
    $output .= "</div>";
  }
  return $output;
}

/**
 * Gets number of the item in the list by it's id.
 *
 * @param mixed $map_set_id
 *   Id of the something.
 * @param array $list
 *   List of something.
 *
 * @return int
 *   Returns number of the item in the list.
 */
function cmap_get_link_group_count($map_set_id, array $list) {
  for ($j = 0; $j < count($list); $j++) {
    if ($list[$j]['map_set_id'] == $map_set_id) {
      return $j;
    }
  }
}
