<?php

/**
 * @file
 * Defines module schema and install/uninstall processes.
 */

/**
 * Implements hook_schema().
 */
function rest_api_schema() {
  $class_list = [
    'RestApiResponse',
    'RestApiRequest',
  ];
  foreach ($class_list as $path) {
    $class_file = dirname(__FILE__) . '/src/' . $path . '.class.inc';
    if (file_exists($class_file)) {
      require_once $class_file;
    }
  }
  $schema[RestApiResponse::TABLE] = RestApiResponse::getSchema();
  $schema[RestApiRequest::TABLE] = RestApiRequest::getSchema();
  return $schema;
}

/**
 * Implements hook_install().
 */
function rest_api_install() {
  variable_set('rest_api_timeout', 30);
  variable_set('rest_api_max_execution_time', 5000);
  variable_set('rest_api_use_cache', TRUE);
  variable_set('rest_api_use_log', TRUE);

  // Let's manually create foreign key (fk) because Drupal7 doesn't support fk.
  // So when request was removed related responses also will be removed to
  // avoid orphan records.
  $sql = '
    ALTER TABLE rest_api_response
    ADD CONSTRAINT fk_response_request
    FOREIGN KEY (request_id)
    REFERENCES rest_api_request (request_id)
    ON DELETE CASCADE;';
  db_query($sql);
}

/**
 * Implements hook_uninstall().
 */
function rest_api_uninstall() {
  variable_del('rest_api_timeout');
  variable_del('rest_api_max_execution_time');
  variable_del('rest_api_use_cache');
  variable_del('rest_api_use_log');
}
